/*
 * This file was generated by gots, do not edit it manually
 * You can find the docs and source code at https://github.com/aosasona/gots
 */
	
export type Language = string;

export type Tags = Record<string, string>;

export type Person = {
    first_name: string;
    last_name: string;
    age: number;
    address: {
        line_1: string | null;
        line_2: string | null;
        street: string;
        city: string;
        state: string;
        postal_code: string;
        country: string;
    };
    languages: string[];
    grades?: Record<string, number>;
    tags: Record<string, string>;
    created_at: number;
    updated_at: number | null;
    deleted_at: number | null;
};