package main

import (
	"fmt"
	"time"

	"go.trulyao.dev/gots"
)

type Language string

type Tags map[string]string

type Address struct {
	Line1      *string `gots:"name:line_1"`
	Line2      *string `gots:"name:line_2"`
	Street     string  `gots:"name:street"`
	City       string  `gots:"name:city"`
	State      string  `gots:"name:state"`
	PostalCode string  `gots:"name:postal_code"`
	Country    string  `gots:"name:country"`
}

type Person struct {
	FName     string `gots:"name:first_name"`
	LName     string `gots:"name:last_name"`
	Age       int    `gots:"name:age"`
	Address   `gots:"name:address"`
	Languages []Language     `gots:"name:languages"`
	Grades    map[string]int `gots:"name:grades,optional:1"`
	Tags      Tags           `gots:"name:tags"`
	CreatedAt time.Time      `gots:"name:created_at"`
	UpdatedAt *time.Time     `gots:"name:updated_at"`
	DeletedAt *time.Time     `gots:"name:deleted_at"`
}

func main() {
	start := time.Now()
	gt := gots.Init(gots.Config{
		Enabled:           gots.Bool(true),
		OutputFile:        gots.String("./examples/example.ts"),
		UseTypeForObjects: gots.Bool(true),
		ExpandObjectTypes: gots.Bool(true),
	})

	gt.Register(*new(Language), Tags{}, Person{})

	defer func(count int) {
		fmt.Printf("Generated %d types in %s\n", count, time.Since(start))
	}(gt.Count())

	err := gt.Execute(true)
	if err != nil {
		fmt.Println(err)
		return
	}
}

// Output:
//
// /**
// * This file was generated by gots, do not edit it manually
// * You can find the docs and source code at https://github.com/aosasona/gots
// */
//
//
// export type Tags = Record<string, string>
//
// export type Language = string
//
// export type Person = {
//     first_name: string;
//     last_name: string;
//     age: number;
//     address: {
//         line_1: string | null;
//         line_2: string | null;
//         street: string;
//         city: string;
//         state: string;
//         postal_code: string;
//         country: string;
//     } | null;
//     languages: string[];
//     grades?: Record<string, number>;
//     tags: Record<string, string>;
//     created_at: number;
//     updated_at: number | null;
//     deleted_at: number | null;
// }
// Generated 3 types in 356.375µs
